/**
 * Eslint@8.14.0 规则集
 */

module.exports = [
  {
    title: 'Possible Problems',
    id: 'possible-problems',
    desc: 'These rules relate to possible logic errors in code:',
    rules: [
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'array-callback-return',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'constructor-super',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'for-direction',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'getter-return',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-async-promise-executor',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-await-in-loop',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-class-assign',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-compare-neg-zero',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-cond-assign',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-const-assign',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-constant-binary-expression',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-constant-condition',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-constructor-return',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-control-regex',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-debugger',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-dupe-args',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-dupe-class-members',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-dupe-else-if',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-dupe-keys',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-duplicate-case',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-duplicate-imports',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-empty-character-class',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-empty-pattern',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-ex-assign',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-fallthrough',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-func-assign',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-import-assign',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-inner-declarations',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-invalid-regexp',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-irregular-whitespace',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-loss-of-precision',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-misleading-character-class',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-new-symbol',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-obj-calls',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-promise-executor-return',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-prototype-builtins',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-self-assign',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-self-compare',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-setter-return',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-sparse-arrays',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-template-curly-in-string',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-this-before-super',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-undef',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-unexpected-multiline',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-unmodified-loop-condition',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-unreachable',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-unreachable-loop',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-unsafe-finally',
      },
      {
        recommend: true,
        fixable: false,
        title: '💡',
        desc: 'no-unsafe-negation',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-unsafe-optional-chaining',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-unused-private-class-members',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-unused-vars',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-use-before-define',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-useless-backreference',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'require-atomic-updates',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'use-isnan',
      },
      {
        recommend: true,
        fixable: false,
        title: '💡',
        desc: 'valid-typeof',
      },
    ],
  },
  {
    title: 'Suggestions',
    id: 'suggestions',
    desc: 'These rules suggest alternate ways of doing things:',
    rules: [
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'accessor-pairs',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'arrow-body-style',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'block-scoped-var',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'camelcase',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'capitalized-comments',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'class-methods-use-this',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'complexity',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'consistent-return',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'consistent-this',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'curly',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'default-case',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'default-case-last',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'default-param-last',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'dot-notation',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'eqeqeq',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'func-name-matching',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'func-names',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'func-style',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'grouped-accessor-pairs',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'guard-for-in',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'id-denylist',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'id-length',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'id-match',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'init-declarations',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'max-classes-per-file',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'max-depth',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'max-lines',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'max-lines-per-function',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'max-nested-callbacks',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'max-params',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'max-statements',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'multiline-comment-style',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'new-cap',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-alert',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-array-constructor',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-bitwise',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-caller',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-case-declarations',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-confusing-arrow',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-console',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-continue',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-delete-var',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-div-regex',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-else-return',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-empty',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-empty-function',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-eq-null',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-eval',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-extend-native',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-extra-bind',
      },
      {
        recommend: true,
        fixable: true,
        title: '',
        desc: 'no-extra-boolean-cast',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-extra-label',
      },
      {
        recommend: true,
        fixable: true,
        title: '',
        desc: 'no-extra-semi',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-floating-decimal',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-global-assign',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-implicit-coercion',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-implicit-globals',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-implied-eval',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-inline-comments',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-invalid-this',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-iterator',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-label-var',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-labels',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-lone-blocks',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-lonely-if',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-loop-func',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-magic-numbers',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-mixed-operators',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-multi-assign',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-multi-str',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-negated-condition',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-nested-ternary',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-new',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-new-func',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-new-object',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-new-wrappers',
      },
      {
        recommend: true,
        fixable: false,
        title: '💡',
        desc: 'no-nonoctal-decimal-escape',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-octal',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-octal-escape',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-param-reassign',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-plusplus',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-proto',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-redeclare',
      },
      {
        recommend: true,
        fixable: true,
        title: '',
        desc: 'no-regex-spaces',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-restricted-exports',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-restricted-globals',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-restricted-imports',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-restricted-properties',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-restricted-syntax',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-return-assign',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-return-await',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-script-url',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-sequences',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-shadow',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-shadow-restricted-names',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-ternary',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-throw-literal',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-undef-init',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-undefined',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-underscore-dangle',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-unneeded-ternary',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-unused-expressions',
      },
      {
        recommend: true,
        fixable: true,
        title: '',
        desc: 'no-unused-labels',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-useless-call',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-useless-catch',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-useless-computed-key',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-useless-concat',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-useless-constructor',
      },
      {
        recommend: true,
        fixable: false,
        title: '💡',
        desc: 'no-useless-escape',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-useless-rename',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-useless-return',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-var',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-void',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-warning-comments',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-with',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'object-shorthand',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'one-var',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'one-var-declaration-per-line',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'operator-assignment',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'prefer-arrow-callback',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'prefer-const',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'prefer-destructuring',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'prefer-exponentiation-operator',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'prefer-named-capture-group',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'prefer-numeric-literals',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'prefer-object-has-own',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'prefer-object-spread',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'prefer-promise-reject-errors',
      },
      {
        recommend: false,
        fixable: false,
        title: '💡',
        desc: 'prefer-regex-literals',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'prefer-rest-params',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'prefer-spread',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'prefer-template',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'quote-props',
      },
      {
        recommend: false,
        fixable: false,
        title: '💡',
        desc: 'radix',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'require-await',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'require-unicode-regexp',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'require-yield',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'sort-imports',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'sort-keys',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'sort-vars',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'spaced-comment',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'strict',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'symbol-description',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'vars-on-top',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'yoda',
      },
    ],
  },
  {
    title: 'Layout & Formatting',
    id: 'layout-formatting',
    desc: 'These rules care about how the code looks rather than how it executes:',
    rules: [
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'array-bracket-newline',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'array-bracket-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'array-element-newline',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'arrow-parens',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'arrow-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'block-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'brace-style',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'comma-dangle',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'comma-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'comma-style',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'computed-property-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'dot-location',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'eol-last',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'func-call-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'function-call-argument-newline',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'function-paren-newline',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'generator-star-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'implicit-arrow-linebreak',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'indent',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'jsx-quotes',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'key-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'keyword-spacing',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'line-comment-position',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'linebreak-style',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'lines-around-comment',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'lines-between-class-members',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'max-len',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'max-statements-per-line',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'multiline-ternary',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'new-parens',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'newline-per-chained-call',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-extra-parens',
      },
      {
        recommend: true,
        fixable: false,
        title: '',
        desc: 'no-mixed-spaces-and-tabs',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-multi-spaces',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-multiple-empty-lines',
      },
      {
        recommend: false,
        fixable: false,
        title: '',
        desc: 'no-tabs',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-trailing-spaces',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'no-whitespace-before-property',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'nonblock-statement-body-position',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'object-curly-newline',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'object-curly-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'object-property-newline',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'operator-linebreak',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'padded-blocks',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'padding-line-between-statements',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'quotes',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'rest-spread-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'semi',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'semi-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'semi-style',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'space-before-blocks',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'space-before-function-paren',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'space-in-parens',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'space-infix-ops',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'space-unary-ops',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'switch-colon-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'template-curly-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'template-tag-spacing',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'unicode-bom',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'wrap-iife',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'wrap-regex',
      },
      {
        recommend: false,
        fixable: true,
        title: '',
        desc: 'yield-star-spacing',
      },
    ],
  },
];
